try:
	a = 1
except ValueError:
	a = 2
finally:
	a = 3
